// Type stub for next/font/local — real types are generated by `next dev`/`next build`
declare module "next/font/local" {
  interface LocalFontOptions {
    src:
      | string
      | Array<{ path: string; weight?: string; style?: string }>;
    variable?: string;
    weight?: string;
    style?: string;
    display?: string;
    preload?: boolean;
    fallback?: string[];
    adjustFontFallback?: boolean | string;
    declarations?: Array<{ prop: string; value: string }>;
  }

  export default function localFont(
    options: LocalFontOptions
  ): {
    className: string;
    style: { fontFamily: string; fontWeight?: number; fontStyle?: string };
    variable: string;
  };
}
